default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: pass
  host: localhost
  pool: 5

development:
  <<: *default
  database: tallguytutoring_development

test:
  <<: *default
  database: tallguytutoring_test

production:
  <<: *default
  database: tallguytutoring_production
